# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/ai-resolve"

    steps:
      - name: Set up git config for private repos
        env:
          TOKEN: ${{ secrets.RO_REPO_ACCESS_TOKEN }}
        run: git config --global url."https://user:${TOKEN}@github.com".insteadOf "https://github.com"
